# Neo4j Settings
neo4j_uri: "bolt://neo4j:7687"

# Provider defaults
llm_provider: "ollama"

# Ollama Defaults
ollama_endpoint: "http://localhost:11434"
ollama_embed_model: "nomic-embed-text"
ollama_llm_model: "mistral"

# OpenAI Defaults
openai_model: "gpt-4o"
openai_embed_model: "text-embedding-3-small"

#
API_URL: "http://localhost:8000/api"

# RAG Settings (Temp and number of chunks to retrieve)
TEMPERATURE: 0.1
RAG_K: 6

# Data directory (for local file uploads and vector store persistence)
DATA_DIR: "./data"

# Environment & Logging
environment: "DEV"
log_dir: "./logs"
log_level: "INFO"
enable_file_logging: true
